### ISSUE TITLE
Add support for Visual Studio 2017 RC

### ISSUE THREAD

**Issue by laurentkempe** [laurentkempe/GitDiffMargin#101]

**Comment by xperiandri** [comment]
Have you examined new extension API improvements that allow to defer whole or partial extension loading to the stage when it is needed?

**Comment by laurentkempe** [comment]
@xperiandri Not yet but @sharwell is having a look to update to latest SDK for Visual Studio RC. After that I will have a look!

**Comment by laurentkempe** [comment]
I just merged the first step of the update done by @sharwell see #113

**Comment by sharwell** [comment]
@xperiandri I don't believe this project will benefit from those API changes. The extension load is already triggered by the specific events where it is needed.
