### ISSUE TITLE
Fix issue to upload on the marketplace

### ISSUE THREAD

**Issue by laurentkempe** [laurentkempe/GitDiffMargin#111]
"This extension targets Visual Studio 2017 but was not built with an up-to-date VSSDK. Please make sure to update your references and try uploading again. Note: you'll also need to add Prerequisites to your extension.vsixmanifest."

**Comment by sharwell** [comment]
I would call this a duplicate of #101.

**Comment by laurentkempe** [comment]
@sharwell #114 fixes the upload on the marketplace! I did not go to the end of the process cause I still have one question concerning installation targets!
