### ISSUE TITLE
Fix installation in Visual Studio 2013 and earlier

### ISSUE THREAD

**Issue by sharwell** [laurentkempe/GitDiffMargin#115]
I suspect installation only works on systems with Visual Studio 2015 and newer installed. This is due to earlier versions not recognizing that the lowest installation target is **Microsoft.VisualStudio.Community**. See tunnelvisionlabs/MouseNavigation#13 for the original bug report drawing this to my attention, as well as the associated pull request for a solution.

:memo: Note that I'm currently waiting for verification that the updated installer works for the user who originally reported the issue.

**Comment by laurentkempe** [comment]
> Note that I'm currently waiting for verification that the updated installer works for the user who originally reported the issue.

Ok let's see when you get feedback! Because I didn't hear anything about it with GitDiffMargin

**Comment by anickle060193** [comment]
I am unable to install an update for GitDiffMargin and receive the following error even though I am running Visual Studio Professional 2013:

![image](https://cloud.githubusercontent.com/assets/5424006/22844797/76c38de2-efa5-11e6-82ce-463cbf00d68f.png)

**Comment by laurentkempe** [comment]
> Note that I'm currently waiting for verification that the updated installer works for the user who originally reported the issue.

@sharwell Did you get some feedback?

**Comment by sharwell** [comment]
@laurentkempe Yes, the feedback was that tunnelvisionlabs/MouseNavigation#14 did in fact fix the issue.

**Comment by laurentkempe** [comment]
@sharwell just realized reading the issue! Thanks, will fix it for GitDiffMargin too then
