### ISSUE TITLE
Make double-clicking on diff bar open `Show Difference`

### ISSUE THREAD

**Issue by jcansdale** [laurentkempe/GitDiffMargin#118]
It is very handy having easy access to the editable diff window. It would be even better if I could simply double-click on the diff bar to get there! 😄

**Comment by laurentkempe** [comment]
@jcansdale You might download a pre-version from [here](https://ci.appveyor.com/api/buildjobs/gxaf96ovhvm9888c/artifacts/GitDiffMargin%2Fbin%2FRelease%2FGitDiffMargin.vsix), you need to rename the .zip to .vsix and install it. You might need to uninstall the previous version if it is already installed.

Let me know what you think about it! Thanks
