### ISSUE TITLE
Able to customize diff color

### ISSUE THREAD

**Issue by Elderry** [laurentkempe/GitDiffMargin#119]
Now the diff color is too light compared the old VS one, hope there's an option to config this.

**Comment by laurentkempe** [comment]
Yes, as it is written on the read me "all colors configurable through Visual Studio Fonts and Colors options"

![image](https://cloud.githubusercontent.com/assets/272612/23945961/cceb7eae-0978-11e7-83ab-25e2728c5e16.png)

**Comment by Elderry** [comment]
Sorry that I didn't find it, thanks!

**Comment by laurentkempe** [comment]
now worries @Elderry
