### ISSUE TITLE
Diff window complains that files have different encodings

### ISSUE THREAD

**Issue by jcansdale** [laurentkempe/GitDiffMargin#127]
When using the `Show Difference` command, the diff window often complains that the files have different encodings.

![image](https://user-images.githubusercontent.com/11719160/27392689-32ab3572-569f-11e7-89c8-4d4ef9d452f1.png)

This is caused by one side having an explicit UTF-8 preamble and and the other side also being UTF-8, but not having the preamble. Visual Studio seems to treat files without an explicit preamble as being Western European (Windows), hence the warning.

In the GitHub for Visual Studio extension, we check the working directory file for a UTF-8 preamble and mirror it when we saving the blob we're comparing it to. See here:
https://github.com/github/VisualStudio/blob/d8930ca879435a87750b6447efcdc9bbc86daa3a/src/GitHub.App/Services/PullRequestService.cs#L325

**Comment by laurentkempe** [comment]
Yeah I have seen that too! Trying your fix right now
