### ISSUE TITLE
refresh update bars after cli commit 

### ISSUE THREAD

**Issue by kylepwarren** [laurentkempe/GitDiffMargin#131]
I pretty much always manage commit/branching/checkout at the command line - don't really feel like VS, or hardly any IDE, have very complete git integration.

Anyhow, I've noticed after I do a commit[at command line], I have to close and reopen VS for the GitDiffMargin[extremely useful plugin, thanks] update/refresh the bars/scroll bar area.

Is there something I can do to have to get the update/refresh without restarting VS?

**Comment by sharwell** [comment]
This should have been working for most repositories starting with version 1.1 (commit 40588d1c5f0eeeea286b9feddb5a342917419c12). Submodules should be supported as well since version 3.0.0 (#51).

**Comment by laurentkempe** [comment]
@kylepwarren I almost only myself works with command line or external tool, and never had that issue! As @sharwell wrote this should work for long! 

Do you have some special repository or a way we could reproduce that?

**Comment by sharwell** [comment]
I also work *exclusively* with external tools, so I'm guessing the issue is something unique to this repository.

**Comment by kylepwarren** [comment]
Nothing special that I can think of. It's just a local repo, no remotes or anything. 
"git version 2.8.3" 
using cygwin/putty to do git stuff.
Just tried again after replies, waited longer, same thing. 
Green lines don't go away after commit.

**Comment by laurentkempe** [comment]
@kylepwarren is the repo public?
I haven't used cygwin for years but I don't see why it would be a problem! @sharwell do you also use cygwin, any idea why it would cause an issue?

**Comment by sharwell** [comment]
@kylepwarren Can you help us narrow this down?

1. Can you try Git for Windows command line and see if the same thing happens (see if it is Cygwin-specific)?
2. Does the same thing happen on other machines (see if it is something specific to one machine)?

**Comment by sharwell** [comment]
:memo: I just tried using Cygwin (Git 2.1.1 there) and still wasn't able to reproduce the problem

**Comment by kylepwarren** [comment]
I just tried doing a commit from the cmd.exe window, and the same thing happened. No update to green lines in VS. It sounds like it must be a problem with my VS settings. I checked in options > Environment > documents... "Reload modified files...", and "Detect when file is changed..." are checked. Trying to think what else might help... It's VS 2015...

**Comment by sharwell** [comment]
@kylepwarren Can you post a screenshot of the green bars?

**Comment by kylepwarren** [comment]
![gitdiff](https://user-images.githubusercontent.com/1758152/29171671-4de42f0a-7dab-11e7-94df-a6de1b563ee9.PNG)

**Comment by sharwell** [comment]
I had a sneaking suspicion this was the issue. That bar is the built-in change margin, not Git Diff Margin. It shows lines changed since you last saved a file (yellow), or changed since you opened the file but already saved (green).

**Comment by kylepwarren** [comment]
Ah, I see, inner lighter green line works as expected. I hope there is a way to hide the built-in one. 

Thanks

**Comment by laurentkempe** [comment]
Yes there is in the settings search for Track change

**Comment by kylepwarren** [comment]
options > text editor > general - uncheck track changes. You can close this when ever.

**Comment by rostov-da** [comment]
For me solution problem - open window TeamExplorer (window Visual Studion for working with git).
