### ISSUE TITLE
Weird conflict with the MoeIde extension

### ISSUE THREAD

**Issue by sylveon** [laurentkempe/GitDiffMargin#137]
![image](https://user-images.githubusercontent.com/6440374/32124348-6f961704-bb35-11e7-8f0d-2871f46be204.png)
The background becomes transparent, making it unreadable, and you can see a kind of mini version of the editor window in background nesting another mini version of the editor
https://github.com/Meowtrix/MoeIDE

**Comment by laurentkempe** [comment]
I never used MoelDE so I have no clue what is happening there.

**Comment by IcyViking** [comment]
@sylveon 
I also had this extension conflict issue. The MoeIDE transparency causes some issues with the popup element. I'm no WPF expert, but I pulled the repo and edited the EditorDiffMarginControl.xaml file.

```xml 
<Border Background="Black"
               BorderBrush="{Binding Foreground, Mode=OneWay}"
               BorderThickness="1,1,1,1"
               Margin="0,-1,0,0"
                Visibility="{Binding IsDiffTextVisible,
                Converter={StaticResource BooleanToVisibilityConverter}}">
  <TextBox Margin="5"
                  BorderThickness="0"
                  IsReadOnly="True"
                  FontFamily="{Binding FontFamily, Mode=OneWay}"
                  FontStretch="{Binding FontStretch, Mode=OneWay}"
                  FontStyle="{Binding FontStyle, Mode=OneWay}"
                  FontWeight="{Binding FontWeight, Mode=OneWay}"
                  FontSize="{Binding FontSize, Mode=OneWay}"
                  Text="{Binding DiffText, Mode=OneWay}"
                   Background="Black"
                   Foreground="{Binding Foreground, Mode=OneWay}"
                   VerticalScrollBarVisibility="Auto"
                   HorizontalScrollBarVisibility="Auto" />
</Border>
```

You can manually set the background here to whatever you want (black tends to be OK for dark themes). Rebuild the GitDiffMargin solution, uninstall the extension via Tools -> Extensions, and run the VSIX file in GitDiffMargin\GitDiffMargin.Extension\bin\Release.

This isn't a long term fix and may be overwritten by automatic updates, but I hope it helps at least.
A better solution could be to disable transparency on the second border, around the text box area. Might require a color converter of some kind.
