### ISSUE TITLE
Bug or Feature Request: UI does not close on Escape

### ISSUE THREAD

**Issue by MartinL0815** [laurentkempe/GitDiffMargin#138]
Hi,

If I open the GitDiffMargin UI by clicking on to the margin, I would like to be able to close it using the escape key.

If this should be working already, something holds GitDiffMargin from receiving and reacting.
If not, I'd like to have this ability, so I don't have to click somewhere in the code to dismiss the GitDiffMargin UI.

Best regards

Martin

**Comment by laurentkempe** [comment]
Hi @MartinL0815 

The only way to hide the popup is to click with the mouse outside of the popup at the moment, but that would be a good combination with your other proposal #140 

Cheers
Laurent

**Comment by MartinL0815** [comment]
Since the floating toolbar or the popup should be able receive the Escape key, why not! ;)

**Comment by laurentkempe** [comment]
I have a version working, I need some polish on it and some test, then I will publish it
