### ISSUE TITLE
Feature Request: another keyboard shortcut to show diff at a change

### ISSUE THREAD

**Issue by MartinL0815** [laurentkempe/GitDiffMargin#140]
Hi,

There is already the ability to assign keyboard shortcuts to jump to the next or previous git related change.

Is there a chance to let the diff and the "floating" toolbar popup, while being with the text cursor within a change?

Best regards,

Martin

**Comment by laurentkempe** [comment]
HI @MartinL0815 

Good idea! I will see what we can do.

**Comment by laurentkempe** [comment]
This will be done with #142

**Comment by laurentkempe** [comment]
This is finally done with version 3.7.0! Download it [here ](https://github.com/laurentkempe/GitDiffMargin/releases/tag/v3.7.0) or wait that it get updated from Visual Studio!
