### ISSUE TITLE
Install Error: extension/package.json not found inside zip.

### ISSUE THREAD

**Issue by DisasterMan78** [laurentkempe/GitDiffMargin#143]
When installing from command palette `Extensions: Install from VSIX...`

VS Code responds with `Error extension/package.json not found inside zip.`

I would guess MS have changed the requirements for extensions if this wasn't needed before.

**Comment by laurentkempe** [comment]
It is a Visual Studio extension not a VS Code one!

**Comment by DisasterMan78** [comment]
Oh right, sorry - didn't realise they weren't compatible.

Struggling to find similar for VS Code.

Apologies for wasting your time.

**Comment by laurentkempe** [comment]
now worries @DisasterMan78

**Comment by DisasterMan78** [comment]
Oddly it seems to be working anyway...

**Comment by DisasterMan78** [comment]
I now realise, having done a new install of VS Code on another machine, that the reason it seems to work is because the feature is baked into  VS Code to begin with.

I just assumed it wouldn't be and went off looking for packages I would want in general without realising.

I now I feel a right prat... 😱

**Comment by laurentkempe** [comment]
@DisasterMan78 Yeah VS Code has this feature bundled into the product 😸
