### ISSUE TITLE
Difference is shown in default VS diff tool, but not in small hint window as before

### ISSUE THREAD

**Issue by ybilianskey** [laurentkempe/GitDiffMargin#144]
[vsdiff.pptx](https://github.com/laurentkempe/GitDiffMargin/files/1741262/vsdiff.pptx)

**Comment by laurentkempe** [comment]
Thanks for the report @ybilianskey 
What is this pptx? Could you attach a screenshot?

**Comment by ybilianskey** [comment]
This is MS Office PowerPoint file with video capture. Actually, for some unknown reason disappeared feature returned back by itself, hence you may ignore this issue. Thanks
