### ISSUE TITLE
VS2013: showing/discarding popup with keyboard doesn't give editor the focus back

### ISSUE THREAD

**Issue by MartinL0815** [laurentkempe/GitDiffMargin#145]
The new wonderful ability to raise the diff popup and to discard it again using hotkeys works in VS2015.
In VS2013 the editor doesn't get the focus back after hitting the Escape key. Thus I have to click into the editor to give it the focus back.
I don't know, if it makes a bit special … I use the VsVim extension.

**Comment by laurentkempe** [comment]
@MartinL0815 I have no clue if it comes from VsVim extension, or not!

I don't have anymore VS2013 installed to try it, could you try it disabling VsVim please?

**Comment by MartinL0815** [comment]
Sorry for the delay!

I disabled the VsVim extension, but observed no change in the behavior.

I use a defined hotkey combination to raise the popup window, I use escape to get back to the text and the text editor does not have the focus, so I need to click into the editor to get the focus back.

**Comment by laurentkempe** [comment]
@MartinL0815 I am back from vacations and will have a look to this, but as I do not have VS2013 installed I might ask you to test the patch, would that be ok for you?

**Comment by MartinL0815** [comment]
Sure, I'll test the tries to fix this behavior on my system.

As comment: If I open the popup/toolbar with a hotkey, use the tab key to get to the "undo" button and apply the "undo", then I get back to the editor in the correct way, so that the editor has the focus.
Eventually an editor action, like setting the caret to the current offset may be enough to resolve this problem.

**Comment by laurentkempe** [comment]
> As comment: If I open the popup/toolbar with a hotkey, use the tab key to get to the "undo" button and apply the "undo", then I get back to the editor in the correct way, so that the editor has the focus.
> Eventually an editor action, like setting the caret to the current offset may be enough to resolve this problem.

Great info! I cannot do what you propose at the moment cause the closing is completely handled on the View side, and there we do not have access to any Visual Studio objects. But with your hint, I will try to do it differently and hopefully it will solve it

**Comment by ricksladkey** [comment]
Using the debugger, I can confirm that the problematic code is in `PopupKeyboardBehavior.cs`:

```c#
        private static void EnableKeyboardInput(Popup popup, bool enabled)
        {
            if (!enabled) return;

            IInputElement element = null;
            popup.Loaded += (sender, args) =>
            {
                popup.Child.Focusable = true;
                popup.Child.IsVisibleChanged += (o, ea) =>
                {
                    if (popup.Child.IsVisible)
                    {
                        element = Keyboard.FocusedElement;
                        Keyboard.Focus(popup.Child);
                    }
                };
            };

            popup.Closed += (sender, args) => Keyboard.Focus(element);
        }
```

When the popup is closed, it returns the focus to whoever loaded it, which in my case was the margin "button" (I clicked with the mouse on the pale green difference strip) with the name `diffControl`.

We really want the `_textView` to get the focus, but I didn't see an easy way to do that.

**Comment by ricksladkey** [comment]
I don't know if this is any help, but you could probably locate the `ITextView` reliably from the visual tree: it's a sibling of the direct ancestor `LeftMargin`:

![image](https://user-images.githubusercontent.com/2680524/40041903-936834e6-57ed-11e8-9fd8-da593cb79a02.png)

**Comment by ricksladkey** [comment]
Last idea (I promise!): Bind the escape key to a noop command, like `ReturnToEditor`, and then you can handle it in the controller logic.

**Comment by laurentkempe** [comment]
> When the popup is closed, it returns the focus to whoever loaded it, which in my case was the margin "button" (I clicked with the mouse on the pale green difference strip) with the name diffControl.
> We really want the _textView to get the focus, but I didn't see an easy way to do that.

You are right @ricksladkey the focus is returned to the button and all your proposals make sense so I think we will come to a fix 😸

**Comment by laurentkempe** [comment]
@MartinL0815 @ricksladkey Could you please uninstall GitDiffMargin and re-install the version you can from [here](https://ci.appveyor.com/api/buildjobs/t2hodvkjld6oi76q/artifacts/GitDiffMargin%2Fbin%2FRelease%2FGitDiffMargin.vsix) and see if it fixes the issue in VS 2013 ?

**Comment by MartinL0815** [comment]
Dear Laurent,
I'll try at Tuesday, back at work.
Happy weekend
Martin 
Martin Lemburg
Berlin / Germany
http://about.me/Martin0815 

Am 17. Mai 2018, 22:29, schrieb Laurent Kempé:
@MartinL0815 @ricksladkey Could you please uninstall GitDiffMargin and re-install the version you can from here and see if it fixes the issue in VS 2013 ?

**Comment by laurentkempe** [comment]
> I'll try at Tuesday, back at work.

@MartinL0815 Did you had time?

**Comment by MartinL0815** [comment]
Sorry Laurent, yes, I took the time just now and yes it seems to work!

**Comment by laurentkempe** [comment]
@MartinL0815 Thanks a lot for the test, I will prepare a new version then!
