### ISSUE TITLE
An exception has been encountered

### ISSUE THREAD

**Issue by thomasdr1958** [laurentkempe/GitDiffMargin#149]
I am getting an error using the newest 3.7.1.88 GitDiffMargin.  The activity log says that the file or assembly Tvl.VisualStudio.Text.Utility.10 could not be loaded.

**Comment by laurentkempe** [comment]
Thanks for the issue report!
As written [in here](https://github.com/laurentkempe/GitDiffMargin/issues/124#issuecomment-320515952) "uninstalling, then re-installing GitDiffMargin fixed it."
Please could you try and let me know if it solves your issue?

**Comment by laurentkempe** [comment]
I got the same crash this morning! I uninstalled, installed again and did not had the problem anymore. Sorry for the inconvenience.
