### ISSUE TITLE
Make AsyncPackage to Load VSPackages in the Background

### ISSUE THREAD

**Issue by laurentkempe** [laurentkempe/GitDiffMargin#154]
See https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-asyncpackage-to-load-vspackages-in-the-background

**Comment by sharwell** [comment]
I can take a look at this. I meant to last time I was working in the code...

**Comment by sharwell** [comment]
Oh, right, this project targets Visual Studio 2012+. IMO `AsyncPackage` is unnecessary overhead in this case. I'm considering implementing a backwards-compatible `AsyncPackage` as part of tunnelvisionlabs/vsbase which could be easily adopted by projects in the future without sacrificing compatibility.

**Comment by laurentkempe** [comment]
According to the post "[Improving the responsiveness of critical scenarios by updating auto load behavior for extensions](https://blogs.msdn.microsoft.com/visualstudio/2018/05/16/improving-the-responsiveness-of-critical-scenarios-by-updating-auto-load-behavior-for-extensions/)" my understanding is that this will become mandatory!

There is a link to do it also for VS 2013!

Don't you think we could drop Visual Studio 2012 support?

**Comment by laurentkempe** [comment]
> GitDiffMargin is not an auto-load extension (it doesn't have [ProvideAutoLoad]), so that article shouldn't apply.

👍 

> We could drop support for 2012, but without a true need to do so it doesn't seem to be what we'd want.

Yeah then there is no need to remove it!

**Comment by laurentkempe** [comment]
@sharwell When I uploaded the 3.8.0 package on the marketplace, I'v got the following warning

> Warnings: 
>The package (GitDiffMargin.GitDiffMarginPackage) class in any VSIX supporting Visual Studio 2015 or later should derive from AsyncPackage instead of Package. Read more about using AsyncPackage here: https://aka.ms/asyncpackage.

Are you sure it is not needed?

**Comment by sharwell** [comment]
You can assign this to me and I'll see if there's anything to do on it.

**Comment by sharwell** [comment]
@laurentkempe I'm filing a bug to update that analyzer to stop reporting the warning for packages like this.
