### ISSUE TITLE
Whole file highlighted as changed

### ISSUE THREAD

**Issue by ambiguousrocket** [laurentkempe/GitDiffMargin#164]
VS 2017 15.7.4

The margin of the entire file is highlighted in blue as soon as any change is made to the file, even if it's just adding a space. In some files, only parts of the file will be highlighted in blue though I haven't been able to identify a pattern with this.

![2018-08-07_17-12-43](https://user-images.githubusercontent.com/42182755/43788361-1e90319a-9a65-11e8-8496-bfd2713fca6e.gif)

Hitting backspace and saving the file doesn't get rid of the blue highlight, though CTRL+Z does. 

The below example shows a file where it doesn't highlight the whole file as changed (see the scroll bar on the right)

![2018-08-07_17-14-49](https://user-images.githubusercontent.com/42182755/43788484-6839da76-9a65-11e8-9d19-c21312324715.gif)

Using the Visual Studio diff tool only highlights those areas as expected. I've tried resetting VS to default settings, reinstalling the extension as well as switching between branches. Any advice on what could be causing this?

Thanks!

**Comment by ricksladkey** [comment]
The most likely explanation is that tabs or line endings are somehow being normalized when you make changes to the file. VsVim doesn't do this, but some other extensions do as well as Visual Studio itself in response to certain editorconfig settings.

Things to try:

- Perform the tests with VsVim disabled (`Ctrl+Shift+F12`)
- Check the file size on disk before and after adding a single character, deleting it and saving

If the problem occurs with VsVim disabled, then it is unlikely that it is related to Vsvim.

If the file size on disk increases or decreases by roughly the number of lines then it is likely that some automatic LF -> CRLF or CRLF -> LF conversion is taking place.

**Comment by laurentkempe** [comment]
Thanks for the report @ambiguousrocket 

Could you check if something the following issue #82 is the same problem?

**Comment by ambiguousrocket** [comment]
Sorry for the late response!

I found out that the issue was only affecting certain branches. The line endings weren't being normalised. It was that the .gitattributes file in those branches had lind endings set to auto hence differences being flagged between the origin and the current file. Thanks for the help.
