### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by laurentkempe** [laurentkempe/GitDiffMargin#165]
Hey @sharwell since I merged #161 I created a release and when I install this release the keyboard shortcuts for NextChange, PreviousChange and ShowPopup aren't working anymore! I tried to reset the keyboard shortcuts in Visual Studio 2017 without luck.

If I load the GitDiffMargin project in VisualStudio 2017 and run in the experimental Visual Studio, there it works!

Any clue why this could happen? You can try with the release, that you can download there https://ci.appveyor.com/project/laurentkempe/gitdiffmargin/branch/master/artifacts

**Comment by olegtk** [comment]
Try adding [ProvideBindingPath] to your package, [like in the sample](https://github.com/Microsoft/VSSDK-Extensibility-Samples/blob/master/Backwards_Compatible_Editor_Command/src/CommandDefinition/JoinLinesCommandPackage.cs#L22). It's currently required unfortunately.

**Comment by sharwell** [comment]
@laurentkempe In my pull request, I didn't use `[ProvideBindingPath]`. I wasn't expecting it to get merged before confirming the approach I used fixed the issue. 😊 I'll send a new pull request to revert that change and try the second approach instead.

**Comment by laurentkempe** [comment]
> I wasn't expecting it to get merged before confirming the approach I used fixed the issue.

oh, sorry about my wrong understanding!
