### ISSUE TITLE
GitDiffMargin v3.7.1.88 crashes after VS 2017 15.8 update

### ISSUE THREAD

**Issue by strandloper** [laurentkempe/GitDiffMargin#169]
I have just updated Visual Studio 2017 to the new 15.8 version and on reopening my solution after the update the latest GitDiffMargin version 3.7.1.88 assembly fails to load due to FileNotFoundException. Here is the ActivityLog.

[ActivityLog.zip](https://github.com/laurentkempe/GitDiffMargin/files/2293209/ActivityLog.zip)

**Comment by laurentkempe** [comment]
Could you update GitDiffMargin to 3.8.0 and tell me if it's fixing the issue, thanks!

**Comment by strandloper** [comment]
Yes, the 3.8.0 version has corrected the problem.
