### ISSUE TITLE
Buttons on change tooltip goes missing

### ISSUE THREAD

**Issue by TeaDrivenDev** [laurentkempe/GitDiffMargin#176]
I've just encountered this for the second time: The reset etc. buttons above the change tooltip simply stopped showing up.

![screenshot - 20180913034303](https://user-images.githubusercontent.com/2247219/45462390-e1751180-b707-11e8-9ad6-1da12dd57d8d.png)

The first time was maybe two weeks ago; I'm not sure if that was already after VS 15.8. The two occurrences were on different machines; this one was only set up less than a week ago. Uninstalling and reinstalling the extension fixed it both times.

(This is currently maybe more for documentation than actually something actionable, as it works now, but maybe there's information I can provide when it happens again.)

**Comment by laurentkempe** [comment]
Thanks for the report @TeaDrivenDev 
We have seen this issue too and we are still having a look from where it comes as written by @sharwell [on Twitter](https://twitter.com/samharwell/status/1039938743573131265)

**Comment by cpowell** [comment]
Saw the same issue here with the latest update. Uninstalled/reinstalled the VSIX, things seem to be working as they should again.

**Comment by TeaDrivenDev** [comment]
I'm closing this. I think I saw the issue once per machine back then, and didn't have it at all on a recent new VS install, so it appears to have been transient and nothing serious.

**Comment by laurentkempe** [comment]
Thanks @TeaDrivenDev
