### ISSUE TITLE
Cleaning dependencies

### ISSUE THREAD

**Issue by laurentkempe** [laurentkempe/GitDiffMargin#200]
@sharwell Any idea why you have added those two dependencies [Newtonsoft.Json](https://github.com/laurentkempe/GitDiffMargin/commit/29ae8a2b93c1dde9f5eada3827bde732bc9f934a#diff-80a82dee8ccca83fcce78f13b3006d88R40) and [StreamJsonRpc](https://github.com/laurentkempe/GitDiffMargin/commit/29ae8a2b93c1dde9f5eada3827bde732bc9f934a#diff-80a82dee8ccca83fcce78f13b3006d88R41)?

**Comment by sharwell** [comment]
I'll clean dependencies and send a PR

**Comment by sharwell** [comment]
Looks like everything is already clean. If you remove these references, you get the following build warnings:

```
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3277: Found conflicts between different versions of "Newtonsoft.Json" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3277: Found conflicts between different versions of "StreamJsonRpc" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
```

**Comment by laurentkempe** [comment]
Yeah weird, I don't know why we have those dependencies!
