### ISSUE TITLE
Leak EventHandler

### ISSUE THREAD

**Issue by calvinhsia** [laurentkempe/GitDiffMargin#240]
Analyzing 40 customer dumps

EvHandler | EvType | PctCabs | CabCnt | AvgNumEVH | MaxNumEVH | Notes | Link
-- | -- | -- | -- | -- | -- | -- | --
System.EventHandler   GitDiffMargin.Core.MarginCore.BrushesChanged +=   GitDiffMargin.ViewModel.ScrollDiffViewModel | MultipleEventHandlers | 1.2 | 40 | 277 | 1596 | https://github.com/laurentkempe/GitDiffMargin
System.EventHandler   GitDiffMargin.Core.MarginCore.BrushesChanged +=   GitDiffMargin.ViewModel.EditorDiffViewModel | MultipleEventHandlers | 1.2 | 40 | 277 | 1596 | https://github.com/laurentkempe/GitDiffMargin

The MarginCore publishes a BrushesChanged event, and the ScrollDiffViewModel and the EditorDiffViewModel subscribe and handle the event, but never unsubscribe.
Thus an average of 277 event subscriptions in each VS session (max 1596) occurs.

## Versions
 - Git Diff Margin version: ...
 - Visual Studio version: ...

**Comment by laurentkempe** [comment]
Thx for the report @calvinhsia I will take a look at it!
