### ISSUE TITLE
Deletion arrows are too big and bright

### ISSUE THREAD

**Issue by kotauskas** [laurentkempe/GitDiffMargin#244]
For me, the deletion arrows feel very big, clumsy and too bright. Below is a comparison between GitDiffMargin and VS Code:
![GitDiffMargin's gutter indicators](https://user-images.githubusercontent.com/28248600/62373103-c1c62200-b541-11e9-8744-76d9a166b75c.png)
![VS Code's gutter indicators](https://user-images.githubusercontent.com/28248600/62373168-e621fe80-b541-11e9-9e21-49a31006d2fe.png)

The VS Code gutter feels nicer, but I might be the only one who thinks this way, so an optimal solution would be an Options page to change the colors of all indicators and the size of the deletion arrows.

**Comment by laurentkempe** [comment]
Thanks for your feedback @kotauskas 

> an optimal solution would be an Options page to change the colors

You are having some good luck there, when you read the feature list it says "all colors configurable through Visual Studio Fonts and Colors options" so head there to configure the color you ❤

For the size, I will keep it in mind the idea of an option, but I always thought that the one from Visual Studio Code are too small and that you can hardly see those! But as you said this is a matter of personal taste.
