### ISSUE TITLE
Blurry text and low quality icons

### ISSUE THREAD

**Issue by TwentyFourMinutes** [laurentkempe/GitDiffMargin#301]
## Versions
 - Git Diff Margin version: 3.10.2.268
 - Visual Studio version: Microsoft Visual Studio Community 2019 Preview Version 16.5.0 Preview 3.0

## What happened
I am actually not sure, if this is issues is caused by the extension itself or something else on my side. Anyhow the text is pretty blurry, as seen in the image below. Additionally the icons are also very low quality, in terms of resolution.

### Steps to Reproduce
1. Open a Solution which is linked to a GitHub repository
2. Change a line of code
3. Check for the difference between the current code and git

### Expected behavior
Same resolution as the other icons in Visual Studio and text which is sharp.

### Screenshots
![image](https://user-images.githubusercontent.com/36015290/75113518-e35a3880-564e-11ea-9627-aecc6f13b601.png)

**Comment by laurentkempe** [comment]
Thanks for the great report @TwentyFourMinutes 
In fact, I am using bitmap icons, cause I don't have vector ones and I am not a designer...

**Comment by TwentyFourMinutes** [comment]
These seem like icons from the Visual Studio Icon library, don't they contain vector version of them? If they do not have them, you need some?

**Comment by laurentkempe** [comment]
Yes @TwentyFourMinutes as far as I remember those are icons from the Visual Studio Icon library!
And yes it seems that now in the 2019 Visual Studio Icon library, they have XAML ones 🎉 
I will update the icon when I have a bit of time to work on that!

**Comment by laurentkempe** [comment]
It start to work using Visual Studio icons!

![image](https://user-images.githubusercontent.com/272612/77107923-ad2b9100-6a21-11ea-937a-957e05d5cd32.png)

**Comment by laurentkempe** [comment]
- [ ] Fix usage for VS2012

See, "[What if my .vsct file also needs to be read by older versions of Visual Studio?](https://docs.microsoft.com/en-us/visualstudio/extensibility/image-service-and-catalog?view=vs-2019#how-do-i-use-image-monikers-in-a-vsct-file)"

**Comment by TwentyFourMinutes** [comment]
Will close the issue once I can verify it later today.

**Comment by laurentkempe** [comment]
> Will close the issue once I can verify it later today.

It is ok, I will close it when I will merge the feature!

**Comment by laurentkempe** [comment]
No more blury text 😄 

![image](https://user-images.githubusercontent.com/272612/78502732-d3139e00-7762-11ea-8431-eb00f6d54ec7.png)

@TwentyFourMinutes Could you try it, [here](https://dev.azure.com/techheadbrothers/GitDiffMargin/_build/results?buildId=375&view=artifacts&type=publishedArtifacts) and let me know what you think, thanks!

**Comment by TwentyFourMinutes** [comment]
Works great and every crisp clean as expected, good job!
![image](https://user-images.githubusercontent.com/36015290/78597170-4eea1500-784d-11ea-9a57-1964ca84b590.png)
