### ISSUE TITLE
Marketplace description says support is up to VS 2019 Preview

### ISSUE THREAD

**Issue by ite-klass** [laurentkempe/GitDiffMargin#380]
On the [marketplace page of this plugin](https://marketplace.visualstudio.com/items?itemName=LaurentKempe.GitDiffMargin) the description says

> Supports Visual Studio 2012 through Visual Studio 2019 Preview.

The GitHub project description says up to VS 2019 _[no preview mentioned]_.

The store description seems confusing if not misleading/wrong and I assume should be corrected to drop Preview.

**Comment by laurentkempe** [comment]
Thanks @ite-klass for taking the time to report this, very much appreciated!
I realized that lately and will fix it soon!

**Comment by laurentkempe** [comment]
In fact, it is already fixed by @sharwell [there](https://github.com/laurentkempe/GitDiffMargin/pull/379/files#diff-2cf56e4c0a98c56ba5e691eac00f146fce56e8bcfc4c210f65df45870968cde3R6).
I will need to publish a new version to fix this.

**Comment by laurentkempe** [comment]
It is now fixed! Thx
![image](https://user-images.githubusercontent.com/272612/111038477-79632b80-8429-11eb-93f2-eeeda8ca3002.png)
