### ISSUE TITLE
Icons are missing from the popup window

### ISSUE THREAD

**Issue by javier-goma** [laurentkempe/GitDiffMargin#383]
## Versions
 - Git Diff Margin version: 3.10.3.462
 - Visual Studio version:  Community 2019 - Version 16.7.3

## What happened
After a change, I wanted to see what was different from the previous commit and I realized that the icons were missing.
I thought it was a theme problem because I use a custom one but even with the VS standard one I see the same problem

### Steps to Reproduce
1. Do any change so that the diff margin can appear
2. Click on the margin so that the popup menu is visible
3. The icons are missing

### Expected behavior
The popup menu should be showing the icons

### Screenshots
![image](https://user-images.githubusercontent.com/69090775/111566070-29a29e00-8762-11eb-96f3-a2834d1194fa.png)

### Additional context
I have tried many things to fix it but not sure what can be, I hope wen can find the solution

Thanks in advance, it's a really great extension

**Comment by laurentkempe** [comment]
Thanks for @javier-goma for taking the time to report this.
I had a quick look with VS 20219 Pro - Version 16.9.1

![image](https://user-images.githubusercontent.com/272612/111624226-b47bab00-87eb-11eb-9d01-f76a13206598.png)

My guess is that it comes from ressources embedding, but I need to investigate.

**Comment by javier-goma** [comment]
Hi @laurentkempe,

I just updated Visual Studio 2019 Community to version 16.9.2 and the icons are being shown

In case you agree, the bug can be closed

Thanks

**Comment by laurentkempe** [comment]
Thanks @javier-goma

**Comment by Otiel** [comment]
After installing GitDiffMargin 3.11.5, I have the same issue using VS 2019 16.9.3.

**Comment by cnotin** [comment]
I had the same problem with the same versions (GitDiffMargin 3.11.5 and VS 2019 Professional 16.10.3)
It fixed itself after disabling the extension, restarting VS, enabling, restart :)

**Comment by Otiel** [comment]
>disabling the extension, restarting VS, enabling, restart

That fixed it for me as well, thanks for the tip @cnotin

**Comment by toughengineer** [comment]
Turning off and on again helped me as well.
All hail the sacred ritual!

**Comment by m2nlight** [comment]
I tryed to reactivate gitmargindiff, then the icons are backed. 
But, if run two vs2019(16.10.3) instance, it’s gone in second instance.

**Comment by laurentkempe** [comment]
This is something we will need to have a look into!

**Comment by sharwell** [comment]
Agree. I'll see what I can find out

**Comment by laurentkempe** [comment]
I will try to have a look next week after vacations
