### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by Tum4ik** [laurentkempe/GitDiffMargin#426]
## Versions
 - Git Diff Margin version: 3.11.5
 - Visual Studio version: 16.10.2

## What happened
Action icons of the live changes are not displayed.

### Steps to Reproduce
1. Go to C# file.
2. Make some changes.
3. Click on the change indicator to get the popup with previous code and actions (jump to prev change, jump to next change, rollback, etc).
4. See the icons of the actions are missing.

### Expected behavior
The action icons have to be visible.

### Screenshots
![image](https://user-images.githubusercontent.com/21317790/124909824-95e82c80-dff3-11eb-9a39-3f478626fa5a.png)

**Comment by laurentkempe** [comment]
See #383 for a workaround

**Comment by Tum4ik** [comment]
Yeah, thanks!

**Comment by Tum4ik** [comment]
Actually, it help only until the PC is rebooted. After that the icons disappear again.

**Comment by laurentkempe** [comment]
Thanks @Tum4ik! Weird, this is something we will have to look at and we already have an issue for it, so closing that one!

**Comment by Tum4ik** [comment]
ok, thanks.
