### ISSUE TITLE
Not working in VS 2022 (Version 17.1.0)

### ISSUE THREAD

**Issue by Ethan-Hall-1080** [laurentkempe/GitDiffMargin#569]
This extension works fine for me when using VS 2019, but does not work for the same Solution when using VS 2022.

![GitDiffMargin Issue](https://user-images.githubusercontent.com/93738475/155672752-811f23e2-d518-4c88-aa1b-de02aef0e937.png)

**Comment by a4armaan** [comment]
Same here, Not working in VS 2022. Can anyone pls help on this?

**Comment by Ethan-Hall-1080** [comment]
I updated to Visual Studio version 17.1.1, and now the addon is working for me.
