### ISSUE TITLE
Move diff bar to the right of the line numbers

### ISSUE THREAD

**Issue by dg9ngf** [laurentkempe/GitDiffMargin#71]
The git Source Control Provider extension shows the diff bar right of the document changes bar, with is right of line numbers. Can GitDiffMargin do the same? I have line numbers enabled everywhere by default because it helps a lot when debugging or reading compile errors or other messages. Now I have two colour bars far away from each other. It would be nice if they were close to each other, preferably in the order that the old GitSCC extension (which is no longer available for VS 2015) uses.

**Comment by laurentkempe** [comment]
Would you please add a screenshot so that I can see it clearly, thanks!

**Comment by dg9ngf** [comment]
![gitdiffbar](https://cloud.githubusercontent.com/assets/868315/6921832/7ddd4e1c-d7c7-11e4-9c8e-695f55fc253a.PNG)

**Comment by laurentkempe** [comment]
Thanks @dg9ngf

**Comment by dg9ngf** [comment]
Here's what it looks like in VS 2010 with GitSCC:

![gitdiffbar2010](https://cloud.githubusercontent.com/assets/868315/6921879/b9d23bc6-d7c7-11e4-9c74-4d5d4f43fdfe.PNG)

**Comment by dg9ngf** [comment]
I found the difference in the source code and have created a pull request: https://github.com/laurentkempe/GitDiffMargin/pull/72
It works here and produces the same diff bar order as in the other extension.

**Comment by laurentkempe** [comment]
:+1: Even better a PR
