### ISSUE TITLE
Make scroll Bars in bar mode diffs clickable to scroll to the position

### ISSUE THREAD

**Issue by laurentkempe** [laurentkempe/GitDiffMargin#76]

**Comment by sharwell** [comment]
I see two problems with this:

1. The diffs are very small and would be hard to reliably click.
2. The other scrollbar overlays do not behave this way.

I recommend not implementing this feature, but instead describe the steps to enable this behavior for the entire scroll bar:

1. Right click the scroll bar &rarr; **Scroll bar options...**
2. Configure the following options:

![image](https://cloud.githubusercontent.com/assets/1408396/9143898/bd9d27aa-3d0e-11e5-9ee5-e65e92bb8d9f.png)

**Comment by laurentkempe** [comment]
I thought of this when I changed from map mode to bar mode, because map mode use too much width when I am on my notebook monitor. It is also a reaction to the way ReSharper is working with the bar mode which allow the user to click on the indicator to scroll to that position, so some overly work that way.
But it is true that the diff can be small, so something to investigate and try but I generally agree with what you wrote, so let's see...

**Comment by sharwell** [comment]
@laurentkempe Map mode is the same size as bar mode when you set **Source overview** to **Off**. :+1:

**Comment by laurentkempe** [comment]
@sharwell Good tip I didn't knew about that! So your recommendation make even more sense!

**Comment by sharwell** [comment]
@laurentkempe Well I *tried* to point it out by highlighting the option in the image. :laughing:

**Comment by laurentkempe** [comment]
@sharwell Nice try but I missed it :-)
