### ISSUE TITLE
VS2015 RTM

### ISSUE THREAD

**Issue by drewnoakes** [laurentkempe/GitDiffMargin#79]
Does this support VS2015 RTM? If so, perhaps the docs could be updated. Also, the copyright year is 2014 in the installer.

**Comment by laurentkempe** [comment]
Not yet, but I will start to adapt it soon! I first need to get VS2015 on my machine

**Comment by sharwell** [comment]
@laurentkempe I've been using it in 2015 without problems for some time now.

**Comment by laurentkempe** [comment]
@sharwell Do you mean that it install correctly with 2015 RTM?

**Comment by drewnoakes** [comment]
Seems to work for me as well. Might just need to update the docs.

**Comment by laurentkempe** [comment]
@drewnoakes It should work, I am just installing VS1015 right now to confirm that it works

**Comment by laurentkempe** [comment]
@drewnoakes @sharwell ok it installs correctly and works correctly in VS2015 RTM!

- [ ] Update description
- [ ] Update copyright
- [ ] Update visualstudiogallery description

**Comment by laurentkempe** [comment]
Thanks @drewnoakes for the feedback!

**Comment by drewnoakes** [comment]
Great. You're welcome. Thanks for the extension!
