### ISSUE TITLE
SQL Server Object Explorer issue

### ISSUE THREAD

**Issue by user1568891** [laurentkempe/GitDiffMargin#81]
Hi,

Using Visual Studio 2015

I get an exception when opening a sql table definition from Visual Studio > SQL Server Object Explorer.

Here is the entry from the ActivityLog.xml:

<type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>
System.ArgumentException: The path is not of a legal form.&#x000D;&#x000A;   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)&#x000D;&#x000A;   at System.IO.Path.GetFullPathInternal(String path)&#x000D;&#x000A;   at GitDiffMargin.DiffMarginFactoryBase.TryGetMarginCore(IWpfTextViewHost textViewHost)&#x000D;&#x000A;   at GitDiffMargin.EditorDiffMarginFactory.CreateMargin(IWpfTextViewHost textViewHost, IWpfTextViewMargin containerMargin)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.&lt;AddMargins&gt;b__3(IWpfTextViewMarginProvider mp)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)       
    </description>

**Comment by laurentkempe** [comment]
@user1568891 ok I can reproduce it here and will have a look!

**Comment by laurentkempe** [comment]
@user1568891 this will be fixed in the next release!
