### ISSUE TITLE
The whole file is highlighted as modified

### ISSUE THREAD

**Issue by mmatrosov** [laurentkempe/GitDiffMargin#82]
If a file has any changes, the whole file is highlighted as modified. The bug is reproduced with all other extensions disabled.

Visual C++ project, C++ file, Visual Studio 2015, Windows 10 x64 (same was under Windows 7 x64), GitDiffMargin v3.1.0.0.

![git diff margin bug](https://cloud.githubusercontent.com/assets/3617951/9418684/7b9ddace-485e-11e5-8b28-3d90c860819a.png)

**Comment by sharwell** [comment]
I've never seen anything like this. My guess is there's another extension which is changing the line endings of the file behind the scenes.

Off the top of my head I'm not quite sure how to debug this. Any ideas @laurentkempe?

**Comment by sharwell** [comment]
Actually, another possibility is the path to the file (including the file name) within the project file in Visual Studio differ from the file on disk by case only.

:question: Try restarting Visual Studio and opening this file *without* opening the solution (just open the file in a fresh copy of Visual Studio. Does the problem still occur?

**Comment by laurentkempe** [comment]
I was also thinking of the line endings. I currently do not have the C++ installed to try reproduce it, will try to install it to have a look

**Comment by mmatrosov** [comment]
Ok, that's what I was able to find out:
1. There is not interference with any other extensions: I disabled all of them
2. There is no difference whether I open the file as a part of a solution or a as an independent file
3. There was no such bug in Visual Studio 2013
4. **If I change line endings from Windows style to Unix style, the bug disappears**

So it seems like your guess was right in the spot!

**Comment by mattwarren** [comment]
I've had exactly the same problem, I only see the real diffs if I change the line ending from Windows to Unix style as @mmatrosov points out (File -> Advanced Save Options...).

The only difference I have is that I see this with a .cs project, not a .cpp one.

But is there a way to make GitDiffMargin work without doing this?

**Comment by laurentkempe** [comment]
@mattwarren Could it be your .gitattributes that set the file to Unix?

**Comment by mmatrosov** [comment]
@laurentkempe Cool. As stated [here](https://help.github.com/articles/dealing-with-line-endings/), if I add `.gitattributes` file with the line `* text=auto` _or_ execute a command `git config --global core.autocrlf true`, the issue is gone. Thank you for the hint!

**Comment by jwidar** [comment]
Hello.

I'm having this issue today 1 march 2019, using the newest version 3.9.2.42 updated automatically by Visual Studio.

![image](https://user-images.githubusercontent.com/15267485/53641142-5a244780-3c2e-11e9-854a-dae2208e696b.png)
The only line I have changed in the file is the one marked in orange. 
According to git, only that line is changed:
![image](https://user-images.githubusercontent.com/15267485/53641363-fd755c80-3c2e-11e9-8be8-4a0f390458e4.png)
I have seen it a few times recently, but cannot remember if it begun today or earlier.

**Comment by jwidar** [comment]
@laurentkempe 
I got rid of the problem mentioned above by reverting to v3.9.0
If I install the one labeled security fix, the problem comes back.
