### ISSUE TITLE
Error: "The supplied SnapshotPoint is on an incorrect snapshot"

### ISSUE THREAD

**Issue by user1568891** [laurentkempe/GitDiffMargin#83]
I got this error today while editing a .cs file in Visual Studio 2015. I'll post more if I can figure out what caused it.

System.ArgumentException: The supplied SnapshotPoint is on an incorrect snapshot.&#x000D;&#x000A;Parameter name: bufferPosition&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.DefaultScrollMap.TranslatePosition(SnapshotPoint bufferPosition)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.DefaultScrollMap.GetCoordinateAtBufferPosition(SnapshotPoint bufferPosition)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.OverviewMargin.Implementation.OverviewMargin.ScrollMapWrapper.GetCoordinateAtBufferPosition(SnapshotPoint bufferPosition)&#x000D;&#x000A;   at GitDiffMargin.ScrollDiffMargin.UpdateDiffDimensions(DiffViewModel diffViewModel, HunkRangeInfo hunkRangeInfo)&#x000D;&#x000A;   at GitDiffMargin.ViewModel.DiffViewModel.UpdateDimensions()&#x000D;&#x000A;   at GitDiffMargin.ViewModel.DiffMarginViewModelBase.RefreshDiffViewModelPositions()&#x000D;&#x000A;   at GitDiffMargin.DiffMarginBase.OnLayoutChanged(Object sender, TextViewLayoutChangedEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent\[TArgs\](Object sender, EventHandler`1 eventHandlers, TArgs args )

Thanks for your work!

**Comment by laurentkempe** [comment]
@user1568891 Any way to reproduce it?

**Comment by darthwalsh** [comment]
I got the same error without ever installing Git Diff Margin, so it could be that the problem is in the base VS editor.

**Comment by user1568891** [comment]
I haven't gotten it in a while. I'll go ahead and close it. If I see it again I'll post.
