### ISSUE TITLE
It seems that this great tool can not show Chinese correctly

### ISSUE THREAD

**Issue by liyu34** [laurentkempe/GitDiffMargin#84]
If I chose the "show Difference", the Chinese words turn to messy code,like this

//��ͷ��Ϣ��ʾ����

and it should be the following words.

//表头信息显示居左

**Comment by laurentkempe** [comment]
@liyu34 Thanks for taking the time to report the problem.

Could you please attach a screenshot of the problem so that I am sure where the problem is!

**Comment by liyu34** [comment]
![bugs](https://cloud.githubusercontent.com/assets/12342277/11087070/fce395ce-8891-11e5-8bda-f5d46e71a39d.png)

**Comment by laurentkempe** [comment]
Thanks @liyu34 for the screenshot, but this is a bug in Visual Studio Diff View nothing to do with Git Diff Margin!
