### ISSUE TITLE
Enabling GitDiffMargin kills Git Source Control Provider

### ISSUE THREAD

**Issue by JohanLarsson** [laurentkempe/GitDiffMargin#85]
Hello,
Not sure who's ~fault~ it is but they don't seem to get along.
After installing margin I get:
![screenie](http://i.imgur.com/huMw1ZX.png)

If I touch anything using [Git Source Control Provider](https://visualstudiogallery.msdn.microsoft.com/51e11ccc-6334-4873-912d-bf5025eb115d)

**Comment by laurentkempe** [comment]
@JohanLarsson Thanks for the report which versions of both tools are you using?

**Comment by JohanLarsson** [comment]
Git Source Control Provider 1.4.2
Git Diff Margin 3.1.0.0
Git Extensions 2.48.05 <- not sure if this has anything to do with anything.
Visual Studio 2015

**Comment by laurentkempe** [comment]
It is weird because in the release notes of Git Source Control Provider 1.4 it is written that they "Removed Git Diff Margin" so any possible interactions between the two shouldn't exists

**Comment by laurentkempe** [comment]
@JohanLarsson I will update LibGit2Sharp to the latest version in the next release of Git Diff Margin, I hope it will fix this!

**Comment by JohanLarsson** [comment]
Nice, thanks!
