### ISSUE TITLE
Crash in git2-785d8c4.dll seen in version 3.1.1.0

### ISSUE THREAD

**Issue by Mathetis** [laurentkempe/GitDiffMargin#92]
Randomly crashes. Seems to happen both in and out of text editor. No symbols, but the trace repeatedly ends up in this dll. 

Microsoft Visual Studio 2015 Pro (14.0.24720.00 Update 1) with Visual Assist. GitTools is also installed.

**Comment by ricksladkey** [comment]
#87

**Comment by laurentkempe** [comment]
I will again update to the latest version of libgit2sharp to see if it improves the situation}

**Comment by laurentkempe** [comment]
Fixed with 3.1.2
