### ISSUE TITLE
Visual Studio 15 support

### ISSUE THREAD

**Issue by xperiandri** [laurentkempe/GitDiffMargin#94]

**Comment by laurentkempe** [comment]
I do not use it at the moment so this will come later or you could add it as a pull request!

**Comment by xperiandri** [comment]
OK
I installed it by modifying manifest. If I encounter any issues I will post them otherwise it will be safe to just modify a manifest.

**Comment by laurentkempe** [comment]
At the moment, it should be enough, except if any API used changed which I don't think is the case but you will see!

**Comment by laurentkempe** [comment]
Duplicates #101
